### ISSUE TITLE
Create initial interface

### ISSUE THREAD

**Issue by DianaKToro** [MCV-Univalle/PlaytherapyWebAdmin#36]
Old interface / New interface
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/75d70d7f-e6a9-4e8c-9463-0de5a9464be5)

**Comment by DianaKToro** [comment]
Old interface / New interface
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/a159a456-7433-4914-ad08-b25ebbaaedac)

**Comment by melissamillares** [comment]
Revisado.
