### ISSUE TITLE
Create home interface

### ISSUE THREAD

**Issue by DianaKToro** [MCV-Univalle/PlaytherapyWebAdmin#38]
Old interface
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/ac143789-9cc2-4ad2-914b-b025126f8887)

New interface
![image.png](https://images.zenhubusercontent.com/5cf97ae8b57ccc6be2abd1b0/c41ac38d-080c-41ef-822f-0dbb63bd3082)

**Comment by melissamillares** [comment]
Revisado.
