### ISSUE TITLE
Definición de reportes básicos

### ISSUE THREAD

**Issue by jpcv222** [MCV-Univalle/PlaytherapyWebAdmin#39]
Se deben definir los reportes básicos que debe tener la aplicación web, de acuerdo a la información que se guarda en la base de datos.

**Comment by jpcv222** [comment]
Se definen reportes por:
- Sesiones
- Terapias
- Movimientos
- FIM

Ver plantillas en: [URL](https://docs.google.com/spreadsheets/d/1cxu_V4eZwyRzXs7pT2o-C-uh1o-LIEFPUufUm63BkyQ/edit?usp=sharing)

**Comment by melissamillares** [comment]
Revisado.
