### ISSUE TITLE
Comparar escala FIM

### ISSUE THREAD

**Issue by mgcc05** [MCV-Univalle/PlaytherapyWebAdmin#40]
Realizar una revisión y comparación del contenido de la escala FIM validada por los fioterapeutas y la que está en el WebAdmin para realizar mejoras y poder complementar.

**Comment by mgcc05** [comment]
[Escala FIM en WebAdmin](https://drive.google.com/open?id=1fRQ0h-mNHPWlmQnNchh78-eZVC8hF6TB)
[Escala FIM del HUV](https://drive.google.com/open?id=1pFLd7qOet0LaikTi8r6Vylt9--nvZawS)
[Calificación FIM](https://drive.google.com/open?id=1i5Z-_2mSXItIlLL18bDL7uEFGxF9aL1u)

En las imágenes se evidencia que en la escala del WebAdmin hacen falta cosas como: las especificaciones de lo que representa la calificación, la fecha en que se realiza la terapia, el terapeuta que realiza la terapia, la cantidad de veces que se van a registrar los puntajes obtenidos de la calificación del paciente, y el puntaje que se tiene como meta alcanzar al finalizar la terapia.

**Comment by mgcc05** [comment]
En las imágenes se evidencia que en la esacala FIM del WebAdmin hacen falta cosas como: las especificaciones para realizar la calificación, la fecha en que se realiza la calificación, el terapeuta que la realiza, la cantidad de veces que se van a registrar los puntajes obtenidos de la calificación al paciente y el puntaje que se quiere alcanzar al finalizar la terapia.

**Comment by melissamillares** [comment]
Revisado.
