### ISSUE TITLE
Prototipar la interaccion

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/PlaytherapyWebAdmin#42]
Para validar con los fisios, se debe prototipar la interaccion final que se tendrá para poder llegar a las tablas de reportes

**Comment by andresow** [comment]
https://ninjamock.com/s/XTS6DGx

**Comment by melissamillares** [comment]
Revisado.
¿Aquí es "Secciones" o "Sesiones"?

![image](https://user-images.githubusercontent.com/26610889/78921866-2f283c00-7a5b-11ea-8603-556f80222945.png)
