### ISSUE TITLE
Generar Token Auth

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/PlaytherapyWebAdmin#43]
Para el sistema de login de django se debe manejar un sistema de tokens.

**Comment by andresow** [comment]
Registro exitoso de usuario, probado con postman, debido a que falta el front-end para conectar
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/527b406a-bcb5-4db5-a338-43b6072e3bfa)
Generacion del token a travez de JWT.
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/5aa92bfb-dac1-49d0-94f1-2a4e00fdeeff)

Token de acceso usado para entrar en la "app"
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/3c968e8c-f5e1-4924-a5c5-a38849442e48)

**Comment by melissamillares** [comment]
Revisado.
