### ISSUE TITLE
API REST FIM

### ISSUE THREAD

**Issue by andresow** [MCV-Univalle/PlaytherapyWebAdmin#5]

**Comment by andresow** [comment]
![image.png](https://images.zenhubusercontent.com/5d14dd72b4a18a460a8e2f5d/a6616819-2320-418e-84c7-d9fb4ae09a11)

**Comment by melissamillares** [comment]
Revisado.

**Comment by melissamillares** [comment]
Recuerden agregar la descripción del issue.
